### ISSUE TITLE
Endpoints Error interlace

### ISSUE THREAD

**Issue by jalax0990** [KathanP19/JSFScan.sh#8] opened 2020-09-01 03:11 UTC
Hello i trying this amazing script but after hours i get this error.

Any way to run the script correctly?

[+] Started Gathering JsFiles-links

[+] Started gathering Endpoints

=====================================================
Interlace v1.8.2	by Michael Skelton (@codingo_)
                  	& Sajeeb Lohani (@sml555_)
=====================================================
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.8.2', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.8.2-py3.8.egg/Interlace/interlace.py", line 32, in main
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.8.2-py3.8.egg/Interlace/interlace.py", line 11, in build_queue
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.8.2-py3.8.egg/Interlace/lib/core/input.py", line 255, in process_commands
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not _io.TextIOWrapper

**Comment by KathanP19** [comment] 2020-09-01 11:05
I think linkfinder is not installed properly

**Comment by KathanP19** [comment] 2020-09-01 12:15
and also can you send a full command you used

**Comment by KathanP19** [comment] 2020-09-01 12:23
I think i have fixed it can you check.

**Comment by jffin** [comment] 2020-09-01 16:26
I have the same issue.
Unfortunately looks like nothing changed.

I'm using this command
```bash JSFScan.sh -l target.txt -e -s -m -o result```


```
+] Started Gathering JsFiles-links


[+] Started gathering Endpoints

=====================================================
Interlace v1.8.2        by Michael Skelton (@codingo_)
                        & Sajeeb Lohani (@sml555_)
=====================================================
Traceback (most recent call last):
  File "/usr/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.8.2', 'console_scripts', 'interlace')()
  File "/usr/lib/python3.8/site-packages/Interlace-1.8.2-py3.8.egg/Interlace/interlace.py", line 32, in main
  File "/usr/lib/python3.8/site-packages/Interlace-1.8.2-py3.8.egg/Interlace/interlace.py", line 11, in build_queue
  File "/usr/lib/python3.8/site-packages/Interlace-1.8.2-py3.8.egg/Interlace/lib/core/input.py", line 255, in process_commands
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not _io.TextIOWrapper```

**Comment by KathanP19** [comment] 2020-09-01 16:57
Try Reinstalling Interlace, the issue is with interlace I guess check their repo for any possible solution.

**Comment by jffin** [comment] 2020-09-01 23:21
@KathanP19 

I created an issue on Interlace GitHub and then used their trick but received a new error.
Is this new issue with your library or still theirs?

```Traceback (most recent call last):
  File "/usr/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.8.2', 'console_scripts', 'interlace')()
  File "/usr/lib/python3.8/site-packages/Interlace-1.8.2-py3.8.egg/Interlace/interlace.py", line 32, in main
  File "/usr/lib/python3.8/site-packages/Interlace-1.8.2-py3.8.egg/Interlace/interlace.py", line 11, in build_queue
  File "/usr/lib/python3.8/site-packages/Interlace-1.8.2-py3.8.egg/Interlace/lib/core/input.py", line 278, in process_commands
Exception: No target provided, or empty target list```

**Comment by jffin** [comment] 2020-09-01 23:32
The last error was because of your library did not able to grab links to "live_jsfile_links.txt" file.

**Comment by jffin** [comment] 2020-09-01 23:51
Seems like everything else is working correctly but here is some more errors if you are interested in.


```Generated 17 commands in total
Repeat set to 1
  0%|                                                                                                                                                         | 0/17 [00:00<?, ?it/s]
mv: can't rename 'index.js': No such file or directory
 35%|███████████████████████████████████████████████████▏                                                                                             | 6/17 [00:09<00:17,  1.57s/it]
mv: can't rename 'index.js': No such file or directory
mv: can't rename '_error.js': No such file or directory
Done! file saved here -> "webpack-035ac2b14bde147cb4a8.js"

Done! file saved here -> "_app.js"

 53%|████████████████████████████████████████████████████████████████████████████▊                                                                    | 9/17 [00:16<00:14,  1.75s/it]
mv: can't rename 'commons.92064d2e3ff47245be45.js': No such file or directory
 65%|█████████████████████████████████████████████████████████████████████████████████████████████▏                                                  | 11/17 [00:17<00:08,  1.48s/it]
mv: can't rename 'main-399d0bd22202ebdbf023.js': No such file or directory
Done! file saved here -> "index.js"

 76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                  | 13/17 [00:21<00:06,  1.64s/it]
mv: can't rename '_error.js': No such file or directory
 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                         | 14/17 [00:22<00:04,  1.38s/it]
mv: can't rename '_app.js': No such file or directory
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 15/17 [00:25<00:03,  1.81s/it]
mv: can't rename 'webpack-42652fa8b82c329c0559.js': No such file or directory
Done! file saved here -> "all.js"

Done! file saved here -> "polyfills-068437943f65be629946.js"

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:32<00:00,  2.26s/it]
mv: can't rename '_app.js': No such file or directory
Done! file saved here -> "main-df5910b01c4df6e13b06.js"

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:34<00:00,  2.26s/it]
mv: can't rename 'main-b95d19086491f8f4f4fd.js': No such file or directory
Done! file saved here -> "commons.0a8d97026a219d39d847.js"

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [01:48<00:00,  6.37s/it]

[+] Manually Search For Secrets Using gf or grep in out/

mv: can't rename 'js_var.txt': No such file or directory```

**Comment by KathanP19** [comment] 2020-09-02 01:29
You can ignore them for now, closing this issue ,thank you for using😄

**Closed by KathanP19** 2020-09-02 01:29 UTC
Labels: question
